[package]
name = "common"
version = "0.1.1"
authors = ["Ashley Wilson <scifilem@gmail.com>"]
edition = "2021"

[dependencies]
bytes = "1.2.1"
slab = "0.4.2"
num-traits = "0.2"
num-derive = "0.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
